config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users
  root 'homepage#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users


end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :account

  mount_uploader :photo, PhotoUploader # Tells rails to use this uploader for this model.
  mount_uploader :sign, SignUploader # Tells rails to use this uploader for this model.
  validates :username, presence: true, uniqueness: true# Make sure the owner's name is present.
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)
    
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:account_id, :cos_id, :account_type, :account_no, :balance)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  #Login
  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      render "new", notice: "username or password is invalid"

    end
  end

  #DELETE current_user
  #Log out
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to edit_user_path(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :name, :mother_name, :father_name, :dob, :aadhar_no, :pan_no, :photo, :sign, :cos_id, :phno, :adress, :nationality)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id, id: :account_account_id %>
  </div>

  <div class="field">
    <%= form.label :cos_id %>
    <%= form.number_field :cos_id, id: :account_cos_id %>
  </div>

  <div class="field">
    <%= form.label :account_type %>
    <%= form.text_field :account_type, id: :account_account_type %>
  </div>

  <div class="field">
    <%= form.label :account_no %>
    <%= form.number_field :account_no, id: :account_account_no %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance, id: :account_balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Cos</th>
      <th>Account type</th>
      <th>Account no</th>
      <th>Balance</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_user %>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.account_id %></td>
        <td><%= account.cos_id %></td>
        <td><%= account.account_type %></td>
        <td><%= account.account_no %></td>
        <td><%= account.balance %></td>
        <td><%= current_user.name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @account.account_id %>
</p>

<p>
  <strong>Cos:</strong>
  <%= @account.cos_id %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @account.account_type %>
</p>

<p>
  <strong>Account no:</strong>
  <%= @account.account_no %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/homepage/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApnaBank</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <% if current_user %>
  Logged in as <%= current_user.username %>.
  <%= link_to "Log Out", logout_path %>
  <% else %>
  <%= link_to "Log In", login_path %>
  <% end %>

  <%= link_to "Sign up", signup_path %>
  <p id="notice"><%= notice %></p><h1>Welcome</h1>
  <p>Welcome to NITK Bank</p>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nitkbank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_edit.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :mother_name %>
    <%= form.text_field :mother_name, id: :user_mother_name %>
  </div>

  <div class="field">
    <%= form.label :father_name %>
    <%= form.text_field :father_name, id: :user_father_name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob, id: :user_dob %>
  </div>

  <div class="field">
    <%= form.label :aadhar_no %>
    <%= form.number_field :aadhar_no, id: :user_aadhar_no %>
  </div>

  <div class="field">
    <%= form.label :pan_no %>
    <%= form.text_field :pan_no, id: :user_pan_no %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :user_photo %>
  </div>

  <div class="field">
    <%= form.label :sign %>
    <%= form.file_field :sign, id: :user_sign %>
  </div>

  <div class="field">
    <%= form.label :cos_id %>
    <%= form.number_field :cos_id, id: :user_cos_id %>
  </div>

  <div class="field">
    <%= form.label :phno %>
    <%= form.number_field :phno, id: :user_phno %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress, id: :user_adress %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality, id: :user_nationality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'edit', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Mother name</th>
      <th>Father name</th>
      <th>Dob</th>
      <th>Aadhar no</th>
      <th>Pan no</th>
      <th>Photo</th>
      <th>Sign</th>
      <th>Cos</th>
      <th>Phno</th>
      <th>Adress</th>
      <th>Nationality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.mother_name %></td>
        <td><%= user.father_name %></td>
        <td><%= user.dob %></td>
        <td><%= user.aadhar_no %></td>
        <td><%= user.pan_no %></td>
        <td><div class="image">
        <%= image_tag( user.photo, :size => "30x20", :crop => :fill) %>
        </div></td>
        <td><div class="image">
        <%= image_tag( user.sign, :size => "30x20", :crop => :fill) %>
        </div></td>
        <td><%= user.cos_id %></td>
        <td><%= user.phno %></td>
        <td><%= user.adress %></td>
        <td><%= user.nationality %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @user.mother_name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @user.father_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<p>
  <strong>Aadhar no:</strong>
  <%= @user.aadhar_no %>
</p>

<p>
  <strong>Pan no:</strong>
  <%= @user.pan_no %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag( @user.photo, :size => "260x180", :crop => :fill) %>
</p>

<p>
  <strong>Sign:</strong>
  <%= image_tag( @user.sign, :size => "260x180", :crop => :fill) %>
</p>

<p>
  <strong>Cos:</strong>
  <%= @user.cos_id %>
</p>

<p>
  <strong>Phno:</strong>
  <%= @user.phno %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @user.adress %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @user.nationality %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>